///
/// @Generated by Mockolo
///






public class ClientMock: Client {
    public init() { }

    public typealias Value = Any

    public private(set) var performCallCount = 0
    public var performHandler: ((Value) async throws -> ())?
    public func perform(value: Value) async throws  {
        performCallCount += 1
        if let performHandler = performHandler {
            try await performHandler(value)
        }
        
    }
}

